### ISSUE TITLE
This should apply to Lutris as well right?

### ISSUE THREAD

**Issue by SourceCodeDeleted** [fearedbliss/ILB#2]
Salutations FeardBliss!
Long time no hear! I think you were on the DevilutionX project for sometime if memory serves well. 

I want to ask, have you tried this in Lutris? I am using DXVK for that as well, but all I receive is the black screen and it makes me wonder if it's not applying this or if there is something else wrong.

Do you have any thoughts on this?

Cheers mate and thank you,

**Comment by fearedbliss** [comment]
Hey @SourceCodeDeleted,

I was part of the original Devilution when it was first released but not in any programming capacity, just testing and a little documentation.

Re: Lutris, I'm not sure. I only use pure wine but also I left Linux a while ago and I'm not sure I'm coming back (FreeBSD on my server and Windows on my desktop. I had FreeBSD on my desktop for a good chunk of this year however).
